/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package flowable

import org.flowable.engine.HistoryService
import org.flowable.engine.RuntimeService
import org.flowable.engine.TaskService
import org.flowable.task.api.Task
import org.flowable.engine.history.HistoricActivityInstance
import spock.lang.Shared
import spock.lang.Specification

class SampleProcessTest extends Specification {
    RuntimeService runtimesvc
    TaskService tasksvc
    HistoryService historysvc

    def setupSpec(){
        ProcessEngine.setSampleProcess()
    }

    def setup(){
        runtimesvc = ProcessEngine.getRunrimeService()
        tasksvc = ProcessEngine.getTaskService()
        historysvc = ProcessEngine.getHistoryService()
    }

    def "start and query task"() {
        setup:
        // タスクを開始する
        HashMap<String, Object> param = [
                employee:"Tambara",
                orOfHolidays:3,
                description:"ワクチンうっちん"
        ]
        def processInstance = runtimesvc.startProcessInstanceByKey("holidayRequest", param)

        when:
        // managers がチェックしなければいけないタスクをクエリする
        List<Task> tasks = tasksvc.createTaskQuery().taskCandidateGroup("managers").list()
        def taskCount1 = tasks.size() // 1件あるはず

        def taskid = tasks.get(0).getId()
        def val = tasksvc.getVariables(taskid)
        def message = "${val.employee} さんが、${val.orOfHolidays}日間の休暇を欲しがっています。「${val.description}」だそうです"

        // タスクを完了させる
        tasksvc.complete(taskid, [approved:true])

        // もうチェックしなければいけないタスクはなくなっている
        tasks = tasksvc.createTaskQuery().taskCandidateGroup("managers").list()
        def taskCount0 = tasks.size() // 0件になっているはず

        // 履歴を取得する。これをどうテストで書けば良いのかはよくわからないので、取得しただけ
        List<HistoricActivityInstance> activities = historysvc.createHistoricActivityInstanceQuery()
                .processInstanceId(processInstance.getId())
                .finished()
                .orderByHistoricActivityInstanceEndTime()
                .asc()
                .list()

        


        then:
        taskCount1 == 1
        message == "Tambara さんが、3日間の休暇を欲しがっています。「ワクチンうっちん」だそうです"

        taskCount0 == 0

    }



}
